spring:
  datasource:
    url: jdbc:postgresql:///bangawo_prod?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=project-bcdbc10f-15a5-46b6-bb3:asia-northeast3:bangawo-prod
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false

springdoc:
  server-url: https://bangawo-server-gzfcbbuf4q-du.a.run.app
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
